import { useState } from "react";
import { Download, HelpCircle, Calendar, TrendingUp, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

const Reports = () => {
  const [selectedTimeRange, setSelectedTimeRange] = useState("1M");

  return (
    <TooltipProvider>
      <div className="p-6 md:p-8 space-y-8">
        {/* Header */}
        <header className="flex flex-col md:flex-row justify-between items-start md:items-center space-y-4 md:space-y-0">
          <div>
            <h1 className="text-3xl font-semibold text-foreground">Investment Reports</h1>
            <p className="text-muted-foreground">Analyze your investment data and download reports.</p>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button className="flex items-center space-x-2">
                <Download className="w-4 h-4" />
                <span>Download Report</span>
                <ChevronDown className="w-4 h-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem>PDF</DropdownMenuItem>
              <DropdownMenuItem>Excel</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </header>

        {/* Report Filters */}
        <Card>
          <CardContent className="p-6">
            <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
              <h2 className="text-xl font-semibold">Report Filters</h2>
              <div className="flex items-center space-x-4">
                <div className="relative">
                  <Calendar className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                  <Input 
                    className="pl-10" 
                    placeholder="Select date range" 
                    defaultValue="Jan 2024 - May 2024"
                  />
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* KPI Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card>
            <CardContent className="p-5">
              <div className="flex items-center mb-1">
                <h3 className="text-lg font-semibold">Total ROI</h3>
                <Tooltip>
                  <TooltipTrigger>
                    <HelpCircle className="w-4 h-4 ml-1 text-muted-foreground" />
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>Return on Investment: Measures the profitability of your investments relative to their cost.</p>
                  </TooltipContent>
                </Tooltip>
              </div>
              <p className="text-3xl font-bold text-green-400">+15.75%</p>
              <p className="text-xs text-muted-foreground mt-1">Since Inception</p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-5">
              <div className="flex items-center mb-1">
                <h3 className="text-lg font-semibold">Top Performing Asset</h3>
                <Tooltip>
                  <TooltipTrigger>
                    <HelpCircle className="w-4 h-4 ml-1 text-muted-foreground" />
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>The asset with the highest percentage gain in the selected period.</p>
                  </TooltipContent>
                </Tooltip>
              </div>
              <p className="text-3xl font-bold">Bitcoin (BTC)</p>
              <p className="text-xs text-green-400 mt-1">+28.5% (YTD)</p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-5">
              <div className="flex items-center mb-1">
                <h3 className="text-lg font-semibold">Avg. Monthly Yield</h3>
                <Tooltip>
                  <TooltipTrigger>
                    <HelpCircle className="w-4 h-4 ml-1 text-muted-foreground" />
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>Average percentage return generated by your investments each month.</p>
                  </TooltipContent>
                </Tooltip>
              </div>
              <p className="text-3xl font-bold">+2.15%</p>
              <p className="text-xs text-muted-foreground mt-1">Last 12 months</p>
            </CardContent>
          </Card>
        </div>

        {/* Charts Section */}
        <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
          {/* Portfolio Growth Chart */}
          <Card className="lg:col-span-3">
            <CardHeader>
              <div className="flex justify-between items-center">
                <CardTitle>Portfolio Growth Over Time</CardTitle>
                <div className="flex space-x-1 bg-muted p-1 rounded-lg">
                  {['1M', '6M', '1Y', 'All'].map((period) => (
                    <Button
                      key={period}
                      variant={selectedTimeRange === period ? "default" : "ghost"}
                      size="sm"
                      onClick={() => setSelectedTimeRange(period)}
                      className="px-3 py-1 text-xs"
                    >
                      {period}
                    </Button>
                  ))}
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="h-80 relative">
                <svg className="absolute inset-0 w-full h-full" viewBox="0 0 500 250">
                  <g>
                    <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="30" y2="30" />
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="35">$150k</text>
                    <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="80" y2="80" />
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="85">$100k</text>
                    <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="130" y2="130" />
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="135">$50k</text>
                    <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="180" y2="180" />
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="185">$25k</text>
                    <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="230" y2="230" />
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="235">$0</text>
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="60" y="245">Jan</text>
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="130" y="245">Feb</text>
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="200" y="245">Mar</text>
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="270" y="245">Apr</text>
                    <text fill="hsl(var(--muted-foreground))" fontSize="10" x="340" y="245">May</text>
                  </g>
                  <g>
                    <defs>
                      <linearGradient id="portfolioGradient" x1="0%" x2="0%" y1="0%" y2="100%">
                        <stop offset="0%" style={{stopColor: "hsl(var(--primary))", stopOpacity: 1}} />
                        <stop offset="100%" style={{stopColor: "hsl(var(--primary))", stopOpacity: 0.2}} />
                      </linearGradient>
                    </defs>
                    <polyline 
                      fill="none" 
                      points="60,200 130,150 200,100 270,80 340,50" 
                      stroke="hsl(var(--primary))" 
                      strokeWidth="2.5"
                    />
                    <circle cx="340" cy="50" fill="hsl(var(--primary))" r="4" stroke="hsl(var(--background))" strokeWidth="2" />
                  </g>
                </svg>
              </div>
            </CardContent>
          </Card>

          {/* Asset Allocation Chart */}
          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle>Asset Allocation</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col">
              <div className="flex-grow flex items-center justify-center relative h-72 md:h-80">
                <svg className="w-full h-full max-w-[200px] md:max-w-[250px]" viewBox="0 0 36 36">
                  <circle 
                    className="transition-all duration-500 ease-out" 
                    cx="18" cy="18" 
                    fill="transparent" 
                    r="15.91549430918954" 
                    stroke="#FBBF24" 
                    strokeDasharray="40 60" 
                    strokeDashoffset="25" 
                    strokeWidth="5"
                    style={{ transform: 'rotate(-90deg)', transformOrigin: '50% 50%' }}
                  />
                  <circle 
                    className="transition-all duration-500 ease-out" 
                    cx="18" cy="18" 
                    fill="transparent" 
                    r="15.91549430918954" 
                    stroke="#60A5FA" 
                    strokeDasharray="25 75" 
                    strokeDashoffset="-15" 
                    strokeWidth="5"
                    style={{ transform: 'rotate(-90deg)', transformOrigin: '50% 50%' }}
                  />
                  <circle 
                    className="transition-all duration-500 ease-out" 
                    cx="18" cy="18" 
                    fill="transparent" 
                    r="15.91549430918954" 
                    stroke="#22C55E" 
                    strokeDasharray="20 80" 
                    strokeDashoffset="-40" 
                    strokeWidth="5"
                    style={{ transform: 'rotate(-90deg)', transformOrigin: '50% 50%' }}
                  />
                  <circle 
                    className="transition-all duration-500 ease-out" 
                    cx="18" cy="18" 
                    fill="transparent" 
                    r="15.91549430918954" 
                    stroke="#F43F5E" 
                    strokeDasharray="10 90" 
                    strokeDashoffset="-60" 
                    strokeWidth="5"
                    style={{ transform: 'rotate(-90deg)', transformOrigin: '50% 50%' }}
                  />
                  <circle 
                    className="transition-all duration-500 ease-out" 
                    cx="18" cy="18" 
                    fill="transparent" 
                    r="15.91549430918954" 
                    stroke="#A78BFA" 
                    strokeDasharray="5 95" 
                    strokeDashoffset="-70" 
                    strokeWidth="5"
                    style={{ transform: 'rotate(-90deg)', transformOrigin: '50% 50%' }}
                  />
                </svg>
              </div>
              <div className="grid grid-cols-2 gap-x-4 gap-y-2 mt-4 text-xs">
                <div className="flex items-center space-x-2">
                  <span className="w-3 h-3 rounded-full bg-[#FBBF24]"></span>
                  <span>Bitcoin (BTC): 40%</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="w-3 h-3 rounded-full bg-[#60A5FA]"></span>
                  <span>Ethereum (ETH): 25%</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="w-3 h-3 rounded-full bg-[#22C55E]"></span>
                  <span>Solana (SOL): 20%</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="w-3 h-3 rounded-full bg-[#F43F5E]"></span>
                  <span>Cardano (ADA): 10%</span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="w-3 h-3 rounded-full bg-[#A78BFA]"></span>
                  <span>Polkadot (DOT): 5%</span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Coin Comparison Chart */}
        <Card>
          <CardHeader>
            <div className="flex justify-between items-center">
              <CardTitle>Coin Comparison</CardTitle>
              <Select defaultValue="price">
                <SelectTrigger className="w-32">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="price">Price</SelectItem>
                  <SelectItem value="market_cap">Market Cap</SelectItem>
                  <SelectItem value="volume">Volume</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardHeader>
          <CardContent>
            <div className="h-96 relative">
              <svg className="absolute inset-0 w-full h-full" viewBox="0 0 500 280">
                <g>
                  <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="30" y2="30" />
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="35">$60k</text>
                  <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="90" y2="90" />
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="95">$40k</text>
                  <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="150" y2="150" />
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="155">$20k</text>
                  <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="210" y2="210" />
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="215">$10k</text>
                  <line stroke="hsl(var(--border))" strokeWidth="0.5" x1="50" x2="490" y1="270" y2="270" />
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="10" y="275">$0</text>
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="60" y="285">Jan</text>
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="140" y="285">Feb</text>
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="220" y="285">Mar</text>
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="300" y="285">Apr</text>
                  <text fill="hsl(var(--muted-foreground))" fontSize="10" x="380" y="285">May</text>
                </g>
                <g>
                  <polyline fill="none" points="60,210 140,160 220,180 300,130 380,60" stroke="#FBBF24" strokeWidth="2.5" />
                  <circle cx="380" cy="60" fill="#FBBF24" r="4" stroke="hsl(var(--background))" strokeWidth="2" />
                  <polyline fill="none" points="60,230 140,220 220,190 300,170 380,140" stroke="#60A5FA" strokeWidth="2.5" />
                  <circle cx="380" cy="140" fill="#60A5FA" r="4" stroke="hsl(var(--background))" strokeWidth="2" />
                  <polyline fill="none" points="60,260 140,250 220,240 300,220 380,200" stroke="#22C55E" strokeWidth="2.5" />
                  <circle cx="380" cy="200" fill="#22C55E" r="4" stroke="hsl(var(--background))" strokeWidth="2" />
                </g>
              </svg>
            </div>
            <div className="flex justify-center space-x-4 mt-3 text-xs">
              <div className="flex items-center space-x-2">
                <span className="w-3 h-3 rounded-full bg-[#FBBF24]"></span>
                <span>Bitcoin (BTC)</span>
              </div>
              <div className="flex items-center space-x-2">
                <span className="w-3 h-3 rounded-full bg-[#60A5FA]"></span>
                <span>Ethereum (ETH)</span>
              </div>
              <div className="flex items-center space-x-2">
                <span className="w-3 h-3 rounded-full bg-[#22C55E]"></span>
                <span>Solana (SOL)</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </TooltipProvider>
  );
};

export default Reports;